server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ordersdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_ADVERTISED_LISTENER}
      group-id: ${KAFKA_GROUP_ID}
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.kafka: DEBUG
    com.mouts.order.api.infrastructure.messaging: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
